### PR TITLE
Migrate logrus

### PR DESCRIPTION
**Pull request by ldez**
Due to the  rename of logrus (Sirupsen -> sirupsen), the logrus package must be updated.

Related to https://github.com/sirupsen/logrus/issues/570 and https://github.com/sirupsen/logrus/pull/384

### CODE REVIEW

**Comment by edeckers** [comment]
Thanks for your MR! I try to have a look at it this weekend.

**Comment by ldez** [comment]
@edeckers any news?

**Comment by edeckers** [comment]
Sorry for the late reply.

Overall it looks good to me: the project builds and works fine. However, I cannot possibly review all changes in the Logrus vendor-update and I hope you can understand I don't want to just trust a random stranger to not have added anything fishy in there.

Therefore I suggest I make a new branch on which I will merge your request, after which I'll replace only your "update vendor"-commit with my own and merge everything into `develop` and `master`.

That works for you?

**Comment by ldez** [comment]
@edeckers That works for me 😃 

FYI I'm a [Træfik](https://github.com/containous/traefik) maintainer, we really need this migration, because we cannot update our Docker dependencies without that.

Thanks for your time.

**Comment by edeckers** [comment]
@ldez I can't quite seem to get the dependencies right in an acceptable amount of time. Can you post the steps to reproduce your result? Just of the single vendor-commit.

**Comment by ldez** [comment]
I switch to the old go1.8.5 (via gvm) and :

```shell
go get -u github.com/sirupsen/logrus
rm -rf Godeps/ vendor/
godep save ./...
```

**Comment by ldez** [comment]
I suggest you to replace the (unmaintained) Godep by https://github.com/golang/dep.

**Comment by edeckers** [comment]
Thanks! I merged your changes and created an issue for replacing Godep. I have no plans for working on that anytime soon though.

**Comment by ldez** [comment]
@edeckers do you have a plan to create a new version/tag?

**Comment by edeckers** [comment]
Yes, I tagged `master` as `v1.0.3`

**Pull request merged**
